automate.py

Fixes #7
Change the logging level of run_traces() results to debug instead of info. The results are still returned to the requester.
N/A

Change log level of run_traces results to debug

---

utils.py

Fixes #6 
The comparison of two endpoints could lead to an Exception when the endpoints does not provide enough information. Endpoints are auto-discovered from flow_stats received, so it might not even be an actual endpoint. The change was made to consider incomplete endpoint information as not equal.
N/A

Fix comparison of endpoints when an endpoint does not provide all necessary fields

---

main.py
settings.py

This PR relates to issue #10. It creates a new setting, `FIND_CIRCUITS_IN_FLOWS`, which allows the operator to enable or disable the `find_circuits` routine. The find_circuits procedure has been shown to consume too many resources while finding circuits in the Flows.

Adding settings to enable/disable find_circuits in flows

---

CHANGELOG.rst
main.py

Fixes #25 
This PR will fix the result of a trace path when using Q-in-Q in an EVC. Basically, tracepath results were reporting the ingress VLAN as being the first item of the entries on each trace step. However, when using Q-in-Q, that parameter will contain a list of VLANs throughout the process. Reporting only the last item of the VLAN list guarantee we are describing the actual traffic behavior.
Some tests were executed to make sure the change didn't break the results of a tracepath:
```
{
"result": [
{
"port": 1,
"time": "2022-05-17 14:33:03.762700",
"type": "starting",
"vlan": 400
},
{
"port": 2,
"time": "2022-05-17 14:33:03.762812",
"type": "trace",
"vlan": 834
},
{
"dpid": "00:00:00:00:00:00:00:03",
"port": 2, …
```

Fix vlan id for trace path result when using Q-in-Q

---

CHANGELOG.rst
automate.py
kytos.json
tests/unit/test_automate.py

Fixes #33 
- Shallow copy on sdntrace_cp to avoid RuntimeError size changed
- Bumped 2022.2.1
- Updated changelog.rst

[Release][Fix] Shallow copy on sdntrace_cp

---

.coveragerc
pytest.ini
requirements/dev.in
requirements/dev.txt
setup.cfg
tests/conftest.py
tests/unit/test_automate.py

- Ugraded core dev dependencies (they needed to be regenerated). It's related to https://github.com/kytos-ng/kytos/pull/284. 
- I've also upgraded `pylint` and fixed linter errors that showed up. 
- For now, `feature/upgrade_dependencies` kytos branch is pinned just so tests pass in the CI. I'll revert this after before this PR gets merged after review. 
This ignored linter error `missing-timeout` will be handled on issue #39

Feature core development dependencies

---

openapi.yml

Fixes #18 
The documentation of PUT /api/amlight/sdntrace_cp/trace endpoint indicated a different structure than expected.
Now I have modified the openapi.yml file to specify the correct structure.

Solving issue on responses of PUT /api/amlight/sdntrace_cp/trace

---

CHANGELOG.rst
automate.py
kytos.json
main.py
tests/unit/test_automate.py
tests/unit/test_main.py
utils.py

Fix issue #48 
The self._circuits structure is removed from sdntrace_cp Automate.
Flows are now fetched from /flow_manager/v2/stored_flows whenever needed.
It is no longer subscribed to the amlight/flow_stats.flows_updated event. 
So, I'm wondering in which case(s) the Main.update_circuits function is called now.
Anyway, the tests pass and things seem well in local tests.
This PR needs to be approved to update flow_stats.

Get the flows from /flow_manager/v2/stored_flows

---

README.rst
utils.py

Fix #54 
Now on the function get_stored_flows() only installed flows are filtered if no state is specified.
See [change](https://github.com/kytos-ng/sdntrace_cp/blob/65b4248d13fd476aa89dcf09e6de0f98bd4815d4/utils.py#L8)

Filter for state=installed by default

---

main.py

Fix #57 
Now, it is ok. See this example:
Request:
```
[
{
"trace": {
"switch": {
"in_port": 2
},
"eth": {
"dl_vlan": 100
}
}
},
{
"trace": {
"switch": {
"in_port": 2
},
"eth": {
"dl_vlan": 101
}
}
}
]
```
Result:
```
{
"00:00:00:00:00:00:00:01": [
[
{
"port": 2,
"time": "2022-12-22 16:10:23.329829",
"type": "starting",
"vlan": 100
}
],
[
{
"port": 2,
"time": "2022-12-22 16:10:23.329881",
"type": "starting",
"vlan": 101
}
]
]
}
```

Fix /traces endpoint in bulk mode

---

CHANGELOG.rst
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

This PR will add information to be used for kytos-ng/mef_eline#245
This PR adds one more piece of information in the control-plane trace output to help consumers identify any missing/misbehaving flow in the last hop of the forwarding process. Before this PR, the correctness of the last hop forwarding rule could not be validated. With this PR, one can compare if the output is how expected.
Before this PR:
1. Sending a trace for intra-switch EVC didn't give any clue about the state of the forwarding rules:
```
{"result":[{"dpid":"00:00:00:00:00:00:00:12","port":1,"time":"2023-01-20 02:16:27.661073","type":"starting","vlan":201}]}
```
2. Sending a trace for an unexisting forwarding rule give pretty much the same result as case 1:
``` …
```

Adding output port information to help traces for intra switch EVCs

---

main.py
tests/unit/test_automate.py
tests/unit/test_main.py

Fix #53 
This PR is a simple change to how traces are executed to avoid the last trace_step being added when it shouldn't. In general, the trace should terminate in the switch with the last flows matching the traced traffic. The way Sdntrace_cp was working before this PR could lead to a final step being added incorrectly.
Some unit tests had to be updated to reflect this new scenario because they were incorrectly processed before, meaning: unit tests were passing just because the entries were added even when the tracing step returned null. With the changes, tests are executed according to the application behavior.
I've also taken this opportunity to refactor some unit tests and avoid code duplication, as well as slightly improve coverage.
- Unit tests: PASSED
- End-to-end tests:
```
+ …
```

Fix issue for trace ending in a NNI

---

CHANGELOG.rst
kytos.json
main.py
openapi.yml
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #74 
This PR is to ensure that empty lists are not returned with `PUT /traces` to avoid errors.
For the request:
```
curl -H 'Content-type: application/json' -X PUT http://127.0.0.1:8181/api/amlight/sdntrace_cp/traces -d '[{"trace": {"switch": {"dpid": "00:00:00:00:00:00:00:01", "in_port": 2}, "eth": {"dl_type": 33024, "dl_vlan": 777}}}]'
```
Now:
```{}```

fix: Return a list of paths with the `PUT /traces` endpoint

---

CHANGELOG.rst
main.py
openapi.yml
tests/unit/test_main.py
utils.py

Closes #61 
Now, it is checked if `actions` is a field of the flow [See link](https://github.com/kytos-ng/sdntrace_cp/blob/86b466560b449b20028512ad4aa1f632bff8946e/main.py#L238).
Now, when running Sdntrace in a switch that has a Flow without actions:
Create a flow for drop packets (no actions):
```
curl -X POST -H 'Content-type: application/json' -d '{"flows": [{"priority": 10, "match": {"in_port": 60, "dl_vlan": 777}}]}' http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:01
```
Run a trace:
```
curl -H 'Content-type: application/json' -X PUT http://127.0.0.1:8181/api/amlight/sdntrace_cp/trace -d '{"trace": {"switch": {"dpid": "00:00:00:00:00:00:00:01", "in_port": 60}, "eth": {"dl_type": 33024, "dl_vlan": 777}}}
```
Response:
``` …
```

fix: Check the `actions` field in flows when running a trace

---

main.py
openapi.yml
tests/unit/test_main.py
utils.py

Closes #63 
This PR validates the presence of the 'dpid' and 'in_port' parameters in the payload for PUT /trace and /traces.
In the case of PUT /trace, when one of the parameters is missing the response is "Bad request", 400
In the case of PUT /traces, requests in which one of the parameters is missing are ignored. See the following examples.
1. `Request`
```
[
{
"trace": {
"switch": {
"in_port": 2
},
"eth": {
"dl_vlan": 100
}
}
},
{
"trace": {
"switch": {
"in_port": 1
},
"eth": {
"dl_vlan": 100
}
}
}
]
```
`Response`
```
{
"00:00:00:00:00:00:00:01": [
[
{
"port": 1,
"time": "2023-02-05 22:00:18.636211",
"type": "starting",
"vlan": 100
},
{
"port": 2,
"time": "2023-02-05 …
```

fix: Validate payload for PUT /trace and /traces

---

CHANGELOG.rst
openapi.yml

This is for #69 
Specifies properties `dpid` and `in_port` as required into the openapi file.
Still need to validate according to the OpenAPI specification, waiting for openapi-core and the validator decorator to be moved to [kytos-ng core](https://github.com/kytos-ng/kytos/issues/261).

doc: Specifies required properties

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Closes #80 
Detects a loop when the input and outgoing interfaces match.
Notice that when the trace contains only one step, it will have the `loop`type if the in_port and out_port match.
Test the same case of the issue.
Response:
```
```
Progress ...

feaure: Add new case of loop when the outgoing interface is the same as the input interface 

---

CHANGELOG.rst
main.py
openapi.yml
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #79 
Map the special `untagged` and `any` values of `vlan` to match the stored flows.
Request:
```
[
{
"trace": {
"switch": {
"in_port": 1
},
"eth": {
"dl_vlan": "untagged"
}
}
},{
"trace": {
"switch": {
"in_port": 1
},
"eth": {
"dl_vlan": "any"
}
}
}
]
```
Answer:
```
{
"result": [
[
{
"port": 1,
"time": "2023-03-16 12:18:33.022395",
"type": "starting",
"vlan": "untagged"
},
{
"out": null,
"port": 2,
"time": "2023-03-16 12:18:33.022927",
"type": "incomplete",
"vlan": 100
}
],
[
{
"out": null,
"port": 1,
"time": "2023-03-16 12:18:33.023045",
"type": "incomplete",
"vlan": "any"
}
]
]
}
```
+ python3 -m pytest …

feature: Support `untagged` and `any` for `vlan`

---

CHANGELOG.rst
main.py
openapi.yml
tests/unit/test_main.py

Closes #63 
This PR is to add validation in `PUT /trace and /traces` with `@validate_openapi` from `kytos.core.helpers`. 
Below is a list of requests, the first one is correct and the rest have errors that the validation should detect.
1. Correct request:
```
[
{
"trace": {
"switch": {
"in_port": 3
},
"eth": {
"         dl_vlan": 10
}
}
}
]
```
Answer:
```
{
"result": [
[
{
"out": null,
"port": 3,
"time": "2023-04-03 16:05:24.858854",
"type": "incomplete"
}
]
]
}
```
Invalid cases:
2. Mandatory parameter missing:
```
[
{
"trace": {
"switch": {
"dpid": "00:00:00:00:00:00:00:01"
},
"eth": {
"         dl_vlan": 10
}
}
}
]
```
Answer:
```
{
"code": 400,
"description": "The request body contains invalid API data. 'in_port' …
```

feature: validate payload

---

CHANGELOG.rst
main.py
openapi.yml

Closes #16 
Closes #17 
Remove `last_id` and `traces`  since  they aren't being used as #16 mentioned.
Remove `GET /api/amlight/sdntrace_cp/trace/{trace_id}` since it does not have an implementation. 
`/traces` continues working well:
Example:
```
[
{
"trace": {
"switch": {
"in_port": 1
}
}
}
]
```
```
{
"result": [
[
{
"port": 1,
"time": "2023-04-10 11:41:30.778149",
"type": "starting"
},
{
"out": null,
"port": 2,
"time": "2023-04-10 11:41:30.778206",
"type": "incomplete"
}
]
]
}
```
N/A

feature: Remove parameters `last_id` and `traces` &  `/{trace_id}` from openapi.yml

---

CHANGELOG.rst
main.py
tests/unit/test_utils.py
utils.py

Closes #88 
When interface not found in a trace, it will be considered an `incomplete` trace. i.e. It is the same case as when t`race_step` early returns None if not flow or not port.
[No warning seen.](https://github.com/kytos-ng/sdntrace_cp/blob/896fe9b9d7afff9aafcdf0d48ce5f395b193fd19/main.py#L183)
progress

Fix issue on interface not found

---

openapi.yml

This is related to PR #91 
Add `last` type & update type to be an enum of string: ["starting", "intermediary", "last", "loop", "incomplete"]
I made sure it loads fine:
```
{
"result": [
[
{
"port": 1,
"time": "2023-04-10 17:01:08.172320",
"type": "starting"
},
{
"out": null,
"port": 2,
"time": "2023-04-10 17:01:08.172398",
"type": "incomplete"
}
]
]
}
```
N/A

Update `type` as enum and add `last` type in openapi.yml

---

CHANGELOG.rst
main.py
openapi.yml
tests/unit/test_main.py

Closes #64 
Add `v1` on `/trace` and `/traces`.
I made sure that `GET /traces` and `GET /trace` work well:
```
curl -H 'Content-type: application/json' -X PUT http://127.0.0.1:8181/api/amlight/sdntrace_cp/v1/trace -d '{"trace": {"switch": {"dpid": "00:00:00:00:00:00:00:01","in_port": 1}}}'
```
```
{"result":[{"dpid":"00:00:00:00:00:00:00:01","port":1,"time":"2023-04-11 19:16:42.264349","type":"starting"},{"dpid":"00:00:00:00:00:00:00:02","out":null,"port":2,"time":"2023-04-11 19:16:42.264406","type":"incomplete"}]}
```
```
curl -H 'Content-type: application/json' -X PUT http://127.0.0.1:8181/api/amlight/sdntrace_cp/v1/traces -d '[{"trace": {"switch": {"dpid": "00:00:00:00:00:00:00:01","in_port": 1}}}]'
```
```
{"result":[[{"dpid":"00:00:00:00:00:00:00:01","port":1,"time":"2023-04-11 …
```

feature: Add v1 routes

---

tests/unit/test_utils.py

Closes #100 
Replace `TestCase` with `pytest` in `test_utils.py`.
`@pytest.mark.parametrize` has been used in some functions and several functions have been grouped together.
N/A
N/A

Replace `TestCase` in `test_utils.py`

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Closes #103 
This is to support `instructions` in `sdntrace_cp` when performing a match.
Same example in issue:
```
{"result":[{"dpid":"00:00:00:00:00:00:00:01","port":1,"time":"2023-08-03 12:21:42.515496","type":"starting"},{"dpid":"00:00:00:00:00:00:00:02","port":2,"time":"2023-08-03 12:21:42.515556","type":"last","vlan":2,"out":{"port":1}}]}
```
[See PR](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/254)

Check for `instructions` in `match_and_apply`

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Closes #104 
This is to support `goto_table` in `sdntrace_cp`.
Send to s1:
```
{
"force": false,
"flows": [
{
"match": {
"in_port": 1
},
"instructions": [
{
"instruction_type": "goto_table",
"table_id": 1
}
]
},
{
"table_id": 1,
"match": {
"in_port": 1
},
"instructions": [
{
"instruction_type": "apply_actions",
"actions": [
{
"action_type": "output",
"port": 3
}
]
}
]
}
]
}
```
Send to s2:
```
{
"force": false,
"flows": [
{
"match": {
"in_port": 3
},
"instructions": [
{
"instruction_type": "goto_table",
"table_id": 2
}
]
},
{
"table_id": 2,
"match": {
"in_port": 3
},
"instructions": [
{
"instruction_type": "apply_actions",
"actions": [
{
"action_type": "output",
"port": 2
}
]
}
]
}
]
}
```
Topology:
```
h11 h11-eth0:s1-eth1
h12 h12-eth0:s1-eth2
h21 h21-eth0:s2-eth1
h22 h22-eth0:s2-eth2
s1 …
```

Support instruction type goto_table

---

CHANGELOG.rst
ui/k-info-panel/show_trace_results.kytos
ui/k-toolbar/main.kytos

Closes #128 
The watchers needed to be updated.
There were some k-inputs that were only being used for display data, so I disabled the ability to write text into them.
After applying the changes I no longer got the errors.

Made changes for vue3sfcloader compatibility

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Closes #127 
K-inputs now use the new customClass prop to add their CSS classes instead of just using class, so that they are compatible with the vue3-sfc-loader.
For these changes to work, you need the latest custom class additions from the main UI repo:
https://github.com/kytos-ng/ui/pull/118#issue-2727981658
I ran it on my local environment and no errors were produced.

Added customClass to k-inputs
